// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace CreatingWindows
{
	public partial class PreferencesWindowController : NSWindowController
	{
		public PreferencesWindowController (IntPtr handle) : base (handle)
		{
		}
	}
}
